# Generated by Django 4.2.17 on 2025-01-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piloto', models.CharField(max_length=100, verbose_name='Nome do Piloto')),
                ('origem', models.CharField(max_length=100, verbose_name='Origem')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
